import assert from 'node:assert/strict';
const base='http://127.0.0.1:8787';
const headers={'oai-authenticated-user-id':'local-test-owner-a','oai-authenticated-user-email':'engineer@example.test'};
const other={'oai-authenticated-user-id':'local-test-owner-b','oai-authenticated-user-email':'reviewer@example.test'};
const id=crypto.randomUUID();
let r=await fetch(base+'/api/projects');assert.equal(r.status,401);
r=await fetch(base+'/api/projects',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({id,name:'API verification project',location:'Test site'})});assert.equal(r.status,200,await r.clone().text());
r=await fetch(base+'/api/projects',{headers});let d=await r.json();assert.ok(d.projects.some(p=>p.id===id));
r=await fetch(base+'/api/projects',{headers:other});d=await r.json();assert.ok(!d.projects.some(p=>p.id===id));
r=await fetch(base+'/api/projects',{method:'POST',headers:{...other,'Content-Type':'application/json'},body:JSON.stringify({id,name:'Unauthorized edit',location:'Test'})});assert.equal(r.status,404);
const text='[OPTIONS]\nFLOW_UNITS CMS\n[JUNCTIONS]\nJ1 10 2\n[OUTFALLS]\nO1 8 FREE\n[CONDUITS]\nC1 J1 O1 50 .013\n[COORDINATES]\nJ1 0 10\nO1 20 0\n';
const form=new FormData();form.append('file',new File([text],'verified.inp'));form.append('projectId',id);
r=await fetch(base+'/api/models',{method:'POST',headers,body:form});assert.equal(r.status,200,await r.clone().text());d=await r.json();assert.equal(d.project.model.units,'CMS');assert.equal(d.project.model.nodes,2);assert.equal(d.project.demo,false);assert.equal(d.project.model.hash.length,64);
r=await fetch(base+'/api/models?projectId='+id,{headers});assert.equal(await r.text(),text);
r=await fetch(base+'/api/models?projectId='+id,{headers:other});assert.equal(r.status,404);
const bad=new FormData();bad.append('file',new File(['bad data'],'bad.inp'));bad.append('projectId',id);r=await fetch(base+'/api/models',{method:'POST',headers,body:bad});assert.equal(r.status,400);
r=await fetch(base+'/api/models?projectId='+id,{headers});assert.equal(await r.text(),text);
r=await fetch(base+'/api/activity?projectId='+id,{headers});d=await r.json();assert.equal(d.events.length,2);
r=await fetch(base+'/api/projects',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:'https://untrusted.example'},body:JSON.stringify({id,name:'Wrong origin',location:'Test'})});assert.equal(r.status,403);
console.log('PASS: auth, persistence, owner isolation, immutable model byte round trip, invalid import rejection, audit trail, origin enforcement.');
