import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runEngine} from './engine-helper.mjs';
const base='http://127.0.0.1:8787';
const owner={'oai-authenticated-user-id':'local-solver-test-a','oai-authenticated-user-email':'solver-a@example.test'};
const other={'oai-authenticated-user-id':'local-solver-test-b','oai-authenticated-user-email':'solver-b@example.test'};
const call=(path,method,body,headers=owner)=>fetch(base+path,{method,headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});
const projectId=crypto.randomUUID();let r=await call('/api/projects','POST',{id:projectId,name:'Solver API verification',location:'Synthetic fixture'});assert.equal(r.status,200);
const input=fs.readFileSync('tests/fixtures/baseline.inp','utf8');const form=new FormData();form.append('projectId',projectId);form.append('file',new File([input],'baseline.inp'));r=await fetch(base+'/api/models',{method:'POST',headers:owner,body:form});assert.equal(r.status,200);const {project}=await r.json();const hash=project.model.hash;
const id=crypto.randomUUID();r=await call('/api/runs','POST',{id,projectId,modelHash:hash,label:'Verified baseline'});assert.equal(r.status,200);
r=await call('/api/runs','POST',{id,projectId,modelHash:hash,label:'Duplicate start'});assert.equal((await r.json()).run.id,id);
r=await call('/api/runs','POST',{id:crypto.randomUUID(),projectId,modelHash:'0'.repeat(64),label:'Stale source'});assert.equal(r.status,409);
const {report}=await runEngine(input);
r=await call('/api/runs','PATCH',{id,status:'completed',elapsedMs:300,report:report.replace('Flow Units ............... CMS','Flow Units ............... CFS')});assert.equal(r.status,400);
r=await call('/api/runs','PATCH',{id,status:'completed',elapsedMs:300,report},other);assert.equal(r.status,404);
r=await call('/api/runs','PATCH',{id,status:'completed',elapsedMs:300,report});assert.equal(r.status,200,await r.clone().text());let run=(await r.json()).run;assert.equal(run.result.floodedNodes,2);assert.equal(run.result.continuityError,-.182);assert.equal(run.reportHash.length,64);
r=await call('/api/runs','PATCH',{id,status:'cancelled',elapsedMs:0,error:'Attempt to alter terminal record'});assert.equal((await r.json()).run.status,'completed');
r=await fetch(base+'/api/runs?id='+id,{headers:owner});assert.equal(await r.text(),report);
r=await fetch(base+'/api/runs?id='+id,{headers:other});assert.equal(r.status,404);
r=await fetch(base+'/api/runs?projectId='+projectId,{headers:other});assert.equal((await r.json()).runs.length,0);
const cancelledId=crypto.randomUUID();await call('/api/runs','POST',{id:cancelledId,projectId,modelHash:hash,label:'Cancellation test'});r=await call('/api/runs','PATCH',{id:cancelledId,status:'cancelled',elapsedMs:1,error:'Cancelled'});assert.equal((await r.json()).run.status,'cancelled');
const raceId=crypto.randomUUID();await call('/api/runs','POST',{id:raceId,projectId,modelHash:hash,label:'Concurrent completion'});const race=await Promise.all([call('/api/runs','PATCH',{id:raceId,status:'completed',elapsedMs:300,report}),call('/api/runs','PATCH',{id:raceId,status:'cancelled',elapsedMs:1,error:'Cancelled'})]);const values=await Promise.all(race.map(r=>r.json()));assert.equal(values[0].run.status,values[1].run.status);
r=await fetch(base+'/api/runs?projectId='+projectId,{headers:owner});assert.equal((await r.json()).runs.length,3);
console.log('PASS: model pinning, start idempotence, original units, owner isolation, server parsing, immutable final state, cancellation, concurrent completion, report round trip.');

const scenarioId=crypto.randomUUID();const experiment={baselineId:id,spec:{kind:'diameter',asset:'C1',percent:25,targetNode:'J1'}};
r=await call('/api/runs','POST',{id:scenarioId,projectId,modelHash:hash,label:'Pipe +25%',experiment});assert.equal(r.status,200,await r.clone().text());const scenario=(await r.json()).run;assert.equal(scenario.experiment.changes[0].after,.375);assert.notEqual(scenario.experiment.inputHash,hash);
r=await fetch(base+'/api/runs?id='+scenarioId+'&input=1',{headers:owner});const modified=await r.text();assert.equal(modified,input.replace('C1 CIRCULAR 0.30','C1 CIRCULAR 0.375'));
r=await fetch(base+'/api/runs?id='+scenarioId+'&input=1',{headers:other});assert.equal(r.status,404);
const scenarioReport=(await runEngine(modified)).report;r=await call('/api/runs','PATCH',{id:scenarioId,status:'completed',elapsedMs:100,report:scenarioReport});assert.equal(r.status,200,await r.clone().text());const finished=(await r.json()).run;assert.ok(finished.comparison.volumeReduction>0);assert.ok(finished.comparison.worsenedNodes.includes('J2'));assert.equal(finished.comparison.eligible,false);
r=await call('/api/runs','POST',{id:crypto.randomUUID(),projectId,modelHash:hash,label:'Invalid parameter',experiment:{...experiment,spec:{...experiment.spec,percent:500}}});assert.equal(r.status,400);
r=await call('/api/runs','POST',{id:crypto.randomUUID(),projectId,modelHash:hash,label:'Nested scenario',experiment:{...experiment,baselineId:scenarioId}});assert.equal(r.status,409);
r=await fetch(base+'/api/models?projectId='+projectId,{headers:owner});assert.equal(await r.text(),input);
r=await fetch(base+'/api/runs?projectId='+projectId+'&options=1',{headers:owner});assert.equal((await r.json()).pipes.length,2);
r=await fetch(base+'/api/runs?projectId='+projectId+'&options=1',{headers:other});assert.equal(r.status,404);
const newForm=new FormData();newForm.append('projectId',projectId);newForm.append('file',new File([input+'\n; new model revision'],'revision.inp'));await fetch(base+'/api/models',{method:'POST',headers:owner,body:newForm});
r=await call('/api/runs','POST',{id:crypto.randomUUID(),projectId,modelHash:hash,label:'Stale experiment',experiment});assert.equal(r.status,409);
r=await fetch(base+'/api/runs?id='+scenarioId+'&input=1',{headers:owner});assert.equal(await r.text(),modified);
console.log('PASS: server-generated changes, separate input hashes, access checks, actual SWMM comparison, downstream harm, invalid/nested/stale rejection, unchanged original, versioned downloads.');
