'use client';
import {useEffect,useRef,useState} from 'react';
import {FlaskConical,Download,LoaderCircle,CloudRain} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {defaultAnalysisConfig,type TestedHypothesis,type StressEvidence} from '@/lib/diagnostics';
import {familyNames,numericalQuality} from '@/lib/experiments';
import {sameId} from '@/lib/inp';
import type {RunRecord} from '@/lib/swmm-results';
import type {AnalysisRecord} from '@/lib/analysis-record';
import type {Project} from '@/lib/drainage';
import {Pick,EvidenceDetails,ReviewWarnings} from './engineering-evidence';
import {SensitivityVisuals} from './sensitivity-visuals';

const active=(a?:AnalysisRecord|null)=>!!a&&['queued','running'].includes(a.status);
export default function AnalysisWorkbench({project,runs,visible}:{project:Project;runs:RunRecord[];visible:boolean}){
 const baselines=runs.filter(r=>r.modelHash===project.model?.hash&&!r.experiment&&r.status==='completed'&&r.verification==='SERVER VERIFIED');
 const [baselineId,setBaselineId]=useState(''),[target,setTarget]=useState(''),[history,setHistory]=useState<AnalysisRecord[]>([]),[analysis,setAnalysis]=useState<AnalysisRecord|null>(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false);
 const [minReduction,setMinReduction]=useState(20),[depthLimit,setDepthLimit]=useState(['CFS','GPM','MGD'].includes(project.model?.units??'')?.492126:.15),[mode,setMode]=useState<'inflow'|'rainfall'>('inflow'),[factors,setFactors]=useState([.75,1,1.25]),[screening,setScreening]=useState(defaultAnalysisConfig('').screening);
 const generation=useRef(0),baseline=baselines.find(r=>r.id===baselineId)??baselines[0];
 const nodes=[...(baseline?.result?.nodes??[])].filter(n=>n.type!=='OUTFALL').sort((a,b)=>b.floodVolume-a.floodVolume);
 const targetNode=nodes.find(n=>n.id===target)?.id??nodes[0]?.id??'';
 const busy=submitting||active(analysis),e=analysis?.evidence;
 useEffect(()=>{let valid=true;fetch(`/api/analyses?projectId=${project.id}`).then(async r=>{const d=await r.json() as {analysis:AnalysisRecord;analyses:AnalysisRecord[];error:string};if(!r.ok)throw new Error(d.error);if(valid){const rows=d.analyses.filter((a:AnalysisRecord)=>a.modelHash===project.model?.hash);setHistory(rows);if(rows[0])void inspect(rows[0].id)}}).catch(e=>valid&&setError(e.message));return()=>{valid=false;generation.current++}},[project.id,project.model?.hash]);
 useEffect(()=>{let valid=true;fetch(`/api/runs?projectId=${project.id}&options=1`).then(async r=>await r.json() as {hydrology?:{rainfallRunoff:boolean}}).then(d=>{if(valid&&d.hydrology?.rainfallRunoff)setMode('rainfall')}).catch(()=>{});return()=>{valid=false}},[project.id]);
 useEffect(()=>{
  if(!active(analysis))return;
  const abort=new AbortController();let timer:ReturnType<typeof setTimeout>;
  async function poll(){try{const r=await fetch(`/api/analyses?id=${analysis!.id}`,{signal:abort.signal});const d=await r.json() as {analysis:AnalysisRecord;analyses:AnalysisRecord[];error:string};if(!r.ok)throw new Error(d.error);if(!abort.signal.aborted){setAnalysis(d.analysis);setHistory(rows=>[d.analysis,...rows.filter(a=>a.id!==d.analysis.id)]);setError('')}}catch(e){if(!abort.signal.aborted)setError((e as Error).message)}finally{if(!abort.signal.aborted)timer=setTimeout(poll,1500)}}
  timer=setTimeout(poll,500);return()=>{abort.abort();clearTimeout(timer)};
 },[analysis?.id,analysis?.status]);
 async function inspect(id:string){const token=++generation.current;try{const r=await fetch(`/api/analyses?id=${id}`);const d=await r.json() as {analysis:AnalysisRecord;analyses:AnalysisRecord[];error:string};if(!r.ok)throw new Error(d.error);if(token===generation.current){setAnalysis(d.analysis);setError('')}}catch(e){if(token===generation.current)setError((e as Error).message)}}
 async function start(){if(!baseline||busy)return;setSubmitting(true);setError('');try{
  const config={...defaultAnalysisConfig(targetNode),minReduction,pondedDepthLimit:depthLimit,screening,scenarios:factors.map((factor,i)=>({label:`Scenario ${String.fromCharCode(65+i)} · ${factor}× ${mode==='inflow'?'supplied inflow':'rainfall'}`,mode,factor}))};
  const r=await fetch('/api/analyses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),projectId:project.id,modelHash:project.model!.hash,baselineId:baseline.id,config})});const d=await r.json() as {analysis:AnalysisRecord;analyses:AnalysisRecord[];error:string};if(!r.ok)throw new Error(d.error);setAnalysis(d.analysis);setHistory(rows=>[d.analysis,...rows]);
 }catch(e){setError((e as Error).message)}finally{setSubmitting(false)}}
 async function cancel(){if(!analysis)return;try{const r=await fetch('/api/analyses',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:analysis.id})});const d=await r.json() as {analysis:AnalysisRecord;analyses:AnalysisRecord[];error:string};if(!r.ok)throw new Error(d.error);setAnalysis(d.analysis)}catch(e){setError((e as Error).message)}}
 function exportEvidence(){const url=URL.createObjectURL(new Blob([JSON.stringify(analysis,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`autopsy-${analysis!.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="analysis-workbench" hidden={!visible}>
 <section className="panel autopsy-setup"><div className="panel-header"><div><span className="badge blue"><FlaskConical size={13}/>AUTOMATIC HOTSPOT AUTOPSY</span><h2>Find the modeled sensitivity. Test the smallest change.</h2><p>One workflow runs independent hypotheses, screens network harm, searches a bounded repair and verifies it under three forcing scenarios.</p></div></div>
 {!baseline?<div className="empty-state"><FlaskConical size={28}/><h3>Run a server-verified baseline first</h3><p>Earlier browser reports remain historical evidence. A trusted baseline is required for automatic diagnosis.</p></div>:<fieldset disabled={busy} className="autopsy-fields"><div className="experiment-form"><Pick label="Reference baseline" value={baseline.id} options={baselines.map(r=>({value:r.id,label:r.label}))} onChange={setBaselineId} disabled={busy}/><Pick label="Hotspot" value={targetNode} options={nodes.map(n=>({value:n.id,label:`${n.id} · ${n.floodVolume.toFixed(3)} ${baseline.result!.volumeUnit}`}))} onChange={setTarget} disabled={busy}/><label className="experiment-field"><span>Minimum flood-volume reduction (%)</span><input type="number" min={1} max={100} value={minReduction} onChange={ev=>setMinReduction(Number(ev.target.value))}/></label><label className="experiment-field"><span>Acceptable ponding ({baseline.result!.depthUnit})</span><input type="number" min={0} step={.01} value={depthLimit} onChange={ev=>setDepthLimit(Number(ev.target.value))}/></label></div>
 <details className="autopsy-settings"><summary>Storm scenarios & engineering screening thresholds</summary><p>Source: USER CONFIGURATION. Multipliers are sensitivity scenarios, not verified design storms or return periods. Only the selected input class is scaled.</p><div className="experiment-form"><Pick label="Scenario forcing" value={mode} options={[{value:'inflow',label:'Direct FLOW hydrographs'},{value:'rainfall',label:'Embedded rain-gage time series'}]} onChange={v=>setMode(v as typeof mode)} disabled={busy}/>{factors.map((factor,i)=><label className="experiment-field" key={i}><span>Scenario {String.fromCharCode(65+i)} multiplier</span><input type="number" min={.25} max={3} step={.05} value={factor} onChange={ev=>setFactors(values=>values.map((v,j)=>i===j?Number(ev.target.value):v))}/></label>)}</div><div className="experiment-form">{Object.entries(screening).map(([key,value])=><label className="experiment-field" key={key}><span>{{pondingM:'Unusual ponding (m)',velocityMps:'Velocity (m/s)',floodHours:'Flood duration (h)',fullFlowRatio:'Max / full flow',headDifferenceM:'Peak head difference (m)'}[key]}</span><input type="number" min={.01} step={.1} value={value} onChange={ev=>setScreening(s=>({...s,[key]:Number(ev.target.value)}))}/></label>)}</div></details>
 <div className="autopsy-actions"><button className="btn primary" onClick={()=>void start()} disabled={busy||!targetNode}><FlaskConical size={17}/>Run hotspot autopsy</button><span>Maximum 12 hypotheses · one-asset repair grid · paired storm simulations</span></div>{!numericalQuality(baseline.result!)&&<p className="error-message">Baseline failed numerical screening. Autopsy will retain evidence but reject candidate selection.</p>}</fieldset>}
 </section>
 {error&&<p role="alert" className="error-message">{error}</p>}
 {active(analysis)&&<section className="panel run-progress" aria-live="polite"><div><LoaderCircle size={20} className="spin"/><strong>{analysis?.progress??analysis?.status}</strong><button className="btn" onClick={()=>void cancel()}>Cancel analysis</button></div><p>The server continues processing when you leave this page. Each simulation uses an isolated worker.</p></section>}
 {analysis?.error&&<p role="alert" className="error-message">{analysis.errorCode&&<strong>{analysis.errorCode}: </strong>}{analysis.error}</p>}
 {history.length>0&&<section className="panel analysis-history"><Pick label="Saved autopsy evidence" value={analysis?.id??''} options={history.map(a=>({value:a.id,label:`${a.config.targetNode} · ${new Date(a.createdAt).toLocaleString()} · ${a.status}`}))} onChange={id=>void inspect(id)} disabled={busy}/>{e&&<div className="title-actions"><button className="btn" onClick={exportEvidence}><Download size={15}/>Export full evidence</button>{analysis?.status==='completed'&&<a className="btn" href={`/api/analyses/report?id=${analysis.id}`} download>Engineering report PDF</a>}</div>}</section>}
 {e&&<>
 <section className="panel diagnosis-summary"><span className="badge green">SERVER VERIFIED · SWMM {e.baseline.result.engineVersion}</span><span className={`badge ${numericalQuality(e.baseline.result)?'green':'red'}`}>Numerical screen {numericalQuality(e.baseline.result)?'PASS':'FAIL'}</span><h2>Dominant modeled sensitivity</h2><h3>{e.dominant??'No supported sensitivity among valid tested hypotheses'}</h3><p>{e.config.targetNode} · configured event · {e.hypotheses.length} hypotheses tested. This finding does not prove a real-world root cause.</p><EvidenceDetails run={e.baseline} jobId={analysis!.id}/></section>
 <SensitivityVisuals e={e}/>
 <section className="panel"><div className="panel-header"><div><h2>Sensitivity ranking</h2><p>Admissibility first; benefit and network response next; smaller changes break close rankings. Rejected runs remain visible.</p></div></div><Table><TableHeader><TableRow>{['HYPOTHESIS','HOTSPOT VOLUME REDUCTION','NETWORK HARM','SCREEN','EVIDENCE'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{e.hypotheses.map((h,i)=><HypothesisRow key={i} hypothesis={h} analysis={analysis!}/>)}</TableBody></Table><details className="untested-families" open><summary>Untested cause families and assets</summary>{e.untested.map((u,i)=><p key={i}><strong>{u.family}: </strong>{u.reason}</p>)}</details></section>
 <section className="panel"><div className="panel-header"><div><h2>Smallest tested admissible intervention</h2><p>{e.search.description}</p></div></div>{e.search.selected?<div className="selected-repair"><span className="badge green">PREFERRED AMONG TESTED OPTIONS IN THIS SEARCH</span><h3>{familyNames[e.search.selected.spec.kind]} · {e.search.selected.spec.asset} · {e.search.selected.spec.percent}%</h3><p>Eligible for engineering review. Physical feasibility, construction cost and calibration remain unverified.</p></div>:<div className="empty-state"><h3>No admissible repair found in this search</h3><p>Expand the declared search or review inputs. No repair or robustness result is fabricated.</p></div>}{e.search.attempts.length>0&&<Table><TableHeader><TableRow>{['TESTED MAGNITUDE','HOTSPOT VOLUME REDUCTION','NETWORK HARM','SCREEN','EVIDENCE'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{e.search.attempts.map((h,i)=><HypothesisRow key={i} hypothesis={h} analysis={analysis!}/>)}</TableBody></Table>}</section>
 <section className="panel"><div className="panel-header"><div><span className="badge blue"><CloudRain size={13}/>SOLVER-BACKED STRESS TEST</span><h2>{e.storms.length?`${e.storms.filter(s=>s.status==='PASS').length} of ${e.storms.length} tested scenarios pass the selected depth, numerical and no-harm screens`:'Storm verification has not run'}</h2><p>Threshold: {e.config.pondedDepthLimit} {e.baseline.result.depthUnit}. Every row pairs a scenario baseline with the same selected intervention.</p></div></div>{e.storms.length?<Table><TableHeader><TableRow>{['SCENARIO','BASELINE PONDING','AFTER PONDING','RESULT','EVIDENCE'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{e.storms.map((s,i)=><StormRow key={i} storm={s} analysis={analysis!}/>)}</TableBody></Table>:<p className="empty-state">An admissible intervention is required before storm verification.</p>}</section>
 <section className="panel inspector-panel"><h2>Assumptions & traceability</h2><p><strong>{e.hydrology.status}</strong> · {e.hydrology.subcatchments} subcatchments · {e.hydrology.rainGages} rain gages · {e.hydrology.infiltrationMethod}</p>{[...e.hydrology.assumptions,...e.limitations].map(l=><p key={l}>{l}</p>)}<p>Source model SHA-256: <code>{e.modelHash}</code></p><p>Network structure SHA-256: <code>{e.networkHash}</code></p><ReviewWarnings warnings={e.baseline.warnings}/></section>
 </>}
 </div>;
}
function HypothesisRow({hypothesis:h,analysis}:{hypothesis:TestedHypothesis;analysis:AnalysisRecord}){
 const base=analysis.evidence!.baseline.result.nodes.find(n=>sameId(n.id,h.spec.targetNode)),after=h.run?.result.nodes.find(n=>sameId(n.id,h.spec.targetNode));
 return <TableRow><TableCell><strong>{familyNames[h.spec.kind]}</strong><small className="block">{h.spec.asset} · {h.spec.percent}%</small></TableCell><TableCell>{h.comparison?.volumeReduction==null?'Unavailable':h.comparison.volumeReduction.toFixed(1)+'%'}</TableCell><TableCell>{h.comparison?h.comparison.worsenedNodes.length?h.comparison.worsenedNodes.join(', '):h.comparison.systemVolumeReduction<-.002?'System volume increased':'None above tolerance':'Not evaluated'}</TableCell><TableCell><span className={`badge ${h.status==='REJECTED'?'red':h.status==='TESTED'?'amber':'green'}`}>{h.status}</span></TableCell><TableCell><details><summary>Inspect</summary><p>{h.rationale}</p>{h.error&&<p className="error-message">{h.error}</p>}{h.changes.map((c,i)=><p key={i}>{c.section} {c.asset}: {c.parameter} {c.before} → {c.after}</p>)}{base&&after&&<p>Node depth {base.maxDepth} → {after.maxDepth} {h.run!.result.depthUnit}; flood volume {base.floodVolume} → {after.floodVolume} {h.run!.result.volumeUnit}; flooding {base.floodHours} → {after.floodHours} h.</p>}{h.comparison?.warnings.map(w=><p key={w}>{w}</p>)}{h.run&&<EvidenceDetails run={h.run} jobId={analysis.id}/>}</details></TableCell></TableRow>;
}
function StormRow({storm:s,analysis}:{storm:StressEvidence;analysis:AnalysisRecord}){
 const target=analysis.config.targetNode;
 const depth=(r?:StressEvidence['baseline'])=>{const n=r?.result.nodes.find(n=>sameId(n.id,target));return n?n.pondedDepth===null?n.floodHours===0?'No flooding':'Depth unavailable':`${n.pondedDepth.toFixed(3)} ${r!.result.depthUnit}`:'Unavailable'};
 return <TableRow><TableCell>{s.scenario.label}</TableCell><TableCell>{depth(s.baseline)}</TableCell><TableCell>{depth(s.intervention)}</TableCell><TableCell><span className={`badge ${s.status==='PASS'?'green':s.status==='WARN'?'amber':'red'}`}>{s.status}</span></TableCell><TableCell><details><summary>Inspect pair</summary>{s.error&&<p className="error-message">{s.error}</p>}{s.changes.map((c,i)=><p key={i}>{c.section} {c.asset} · {c.parameter}: {c.before} → {c.after}</p>)}{s.comparison?.warnings.map(w=><p key={w}>{w}</p>)}{s.baseline&&<><strong>Scenario baseline</strong><EvidenceDetails run={s.baseline} jobId={analysis.id}/></>}{s.intervention&&<><strong>Selected intervention</strong><EvidenceDetails run={s.intervention} jobId={analysis.id}/></>}</details></TableCell></TableRow>;
}
