'use client';
import {useEffect,useState} from 'react';
import {TriangleAlert,ShieldCheck,Download} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {SolverResult} from '@/lib/swmm-results';
import type {SimulationEvidence} from '@/lib/diagnostics';
import type {ReviewWarning,inspectHydrology} from '@/lib/integrity';
export function Pick({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;disabled?:boolean}){return <label className="experiment-field"><span>{label}</span><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue placeholder="Select an option"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>}
export function ReviewNotice(){return <aside className="engineering-notice"><ShieldCheck size={20}/><div><strong>ENGINEERING DECISION SUPPORT</strong><p>DrainageDoctor evaluates behavior within the supplied hydraulic model. Results depend on inputs, boundary conditions, calibration and assumptions. Professional engineering review is required.</p></div></aside>}
export function ReviewWarnings({warnings}:{warnings:ReviewWarning[]}){return <details className="review-warnings" open={warnings.some(w=>w.severity==='error'||w.code==='excessive-ponding')}><summary><TriangleAlert size={17}/> {warnings.length} engineering screening notes</summary><p className="subtle">Screening rules are not regulatory requirements. Numerical validity does not establish physical validity.</p>{warnings.map((w,i)=><p key={i} className={w.severity==='error'?'error-message':''}><strong>{w.asset?`${w.asset} · `:''}{w.code}: </strong>{w.message}<small className="block subtle">Source: {w.source}</small></p>)}</details>}
export function HydraulicMetrics({result:r}:{result:SolverResult}){return <div className="metrics-grid real-metrics">{[['Flooding nodes',String(r.floodedNodes),'of '+r.nodes.length+' nodes'],['Peak reported ponding',r.peakPondedDepth===null?'Not reported':r.peakPondedDepth.toFixed(3),r.depthUnit],['Summed flood volume',r.totalFloodVolume.toFixed(3),r.volumeUnit],['Routing continuity',r.continuityError===null?'Unavailable':`${r.continuityError}%`,'Screening ±1%']].map(([title,value,unit])=><div className="metric" key={title}><div className="metric-label">{title}</div><div className="metric-value">{value}</div><div className="metric-note">{unit}</div></div>)}</div>}
export function HydraulicTable({result:r}:{result:SolverResult}){return <Table><TableHeader><TableRow>{['NODE',`MAX DEPTH (${r.depthUnit})`,`PONDING (${r.depthUnit})`,`FLOOD VOLUME (${r.volumeUnit})`,'FLOODING (h)'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{[...r.nodes].sort((a,b)=>b.floodVolume-a.floodVolume).map(n=><TableRow key={n.id}><TableCell><strong>{n.id}</strong><small className="block subtle">{n.type}</small></TableCell><TableCell>{n.maxDepth.toFixed(3)}</TableCell><TableCell>{n.pondedDepth===null?'Not reported':n.pondedDepth.toFixed(3)}</TableCell><TableCell>{n.floodVolume.toFixed(3)}</TableCell><TableCell>{n.floodHours.toFixed(2)}</TableCell></TableRow>)}</TableBody></Table>}
export function EvidenceDetails({run,jobId}:{run:SimulationEvidence;jobId:string}){
 const url=(hash:string,extension:string)=>`/api/analyses?id=${jobId}&artifact=${hash}.${extension}`;
 return <details className="evidence-details"><summary>Input → solver → result → warnings</summary><p><span className="badge green">{run.verification}</span> EPA SWMM {run.result.engineVersion} · {run.result.routing} · {run.result.flowUnits} · {run.enginePackage}</p><p>Executed: {new Date(run.executedAt).toLocaleString()} · {(run.elapsedMs/1000).toFixed(2)} s</p><p>Continuity: {run.result.continuityError??'Unavailable'}% · non-convergence: {run.result.nonConvergingPercent??'Not reported'}%</p><dl className="hash-list">{[['Input SHA-256',run.inputHash],['Report SHA-256',run.reportHash],['Binary output SHA-256',run.outputHash],['Engine SHA-256',run.engineHash]].map(([k,v])=><div key={k}><dt>{k}</dt><dd><code>{v}</code></dd></div>)}</dl><div className="title-actions">{[[run.inputHash,'inp'],[run.reportHash,'rpt'],[run.outputHash,'out']].map(([hash,extension])=><a className="btn" key={extension} href={url(hash,extension)}><Download size={14}/>{extension.toUpperCase()}</a>)}</div><ReviewWarnings warnings={run.warnings}/><HydraulicTable result={run.result}/></details>;
}
export function HydrologyInspector({projectId}:{projectId:string}){
 const [data,setData]=useState<{hydrology:ReturnType<typeof inspectHydrology>;warnings:ReviewWarning[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch(`/api/runs?projectId=${projectId}&options=1`,{signal:abort.signal}).then(async r=>{const d=await r.json() as NonNullable<typeof data> & {error:string};if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[projectId]);
 if(error)return <p role="alert" className="error-message">{error}</p>;
 if(!data)return <p>Inspecting model hydrology…</p>;
 const h=data.hydrology;
 return <section className="panel inspector-panel"><div className="panel-header"><div><span className={`badge ${h.rainfallRunoff?'blue':'amber'}`}>{h.status}</span><h2>Hydrology integrity inspector</h2></div></div><dl className="inspector-grid">{[['Rainfall-runoff',h.rainfallRunoff?'ACTIVE':'NOT ACTIVE'],['Subcatchments',h.subcatchments],['Rain gages',h.rainGages],['Time series',h.timeSeries],['Infiltration',h.infiltrationMethod],['External flow inputs',h.externalInflows],['Flow units',h.units],['Routing',h.routing],['Simulation starts',h.period.start],['Simulation ends',h.period.end],['Routing timestep',h.routingStep],['Wet timestep',h.wetStep],['Reporting timestep',h.reportStep],['Antecedent dry days',h.antecedentDryDays]].map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="inspector-assumptions">{h.assumptions.map(a=><p key={a}><TriangleAlert size={14}/> {a}</p>)}</div><ReviewWarnings warnings={data.warnings}/></section>;
}
