'use client';
import {useEffect,useRef,useState} from 'react';
import {Activity,Download,LoaderCircle,RefreshCw} from 'lucide-react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import type {Project} from '@/lib/drainage';
import type {RunRecord} from '@/lib/swmm-results';
import type {ExperimentSpec} from '@/lib/experiments';
import {numericalQuality} from '@/lib/experiments';
import ExperimentStudio from './experiment-studio';
import AnalysisWorkbench from './analysis-workbench';
import {HydrologyInspector,HydraulicMetrics,HydraulicTable,ReviewNotice,ReviewWarnings} from './engineering-evidence';

const active=(r:RunRecord)=>['queued','running'].includes(r.status)&&r.source==='server-swmm';
export default function LiveAnalysis({project,view,runRequest=0,onView}:{project:Project;view:string;runRequest?:number;onView:(v:string)=>void}){
 const [runs,setRuns]=useState<RunRecord[]>([]),[selected,setSelected]=useState(''),[submitting,setSubmitting]=useState(false),[error,setError]=useState(''),[label,setLabel]=useState('Baseline · embedded model inputs'),[activity,setActivity]=useState<{event:string;created_at:string}[]>([]);
 const trigger=useRef(runRequest),mounted=useRef(true),busy=submitting||runs.some(active);
 const selectedRun=runs.find(r=>r.id===selected)??runs.find(r=>r.status==='completed'&&r.modelHash===project.model?.hash),result=selectedRun?.modelHash===project.model?.hash?selectedRun?.result:undefined;
 async function load(){const r=await fetch(`/api/runs?projectId=${project.id}`);const d=await r.json() as {run:RunRecord;runs:RunRecord[];events:{event:string;created_at:string}[];error:string};if(!r.ok)throw new Error(d.error);if(mounted.current)setRuns(d.runs)}
 useEffect(()=>{mounted.current=true;load().catch(e=>setError(e.message));return()=>{mounted.current=false}},[project.id]);
 const pendingIds=runs.filter(active).map(r=>r.id).join(',');
 useEffect(()=>{if(!pendingIds)return;let stopped=false,timer:ReturnType<typeof setTimeout>;async function poll(){try{await load();if(!stopped)setError('')}catch(e){if(!stopped)setError((e as Error).message)}finally{if(!stopped)timer=setTimeout(poll,1500)}}timer=setTimeout(poll,500);return()=>{stopped=true;clearTimeout(timer)}},[pendingIds]);
 useEffect(()=>{if(runRequest!==trigger.current){trigger.current=runRequest;void start()}},[runRequest]);
 useEffect(()=>{if(view==='Activity log')fetch(`/api/activity?projectId=${project.id}`).then(async r=>{const d=await r.json() as {run:RunRecord;runs:RunRecord[];events:{event:string;created_at:string}[];error:string};if(!r.ok)throw new Error(d.error);setActivity(d.events)}).catch(e=>setError(e.message))},[view,project.id]);
 async function start(spec?:ExperimentSpec,baselineId?:string){
  if(busy)return;if(!project.model){setError('Import a SWMM model first.');return}setSubmitting(true);setError('');
  try{const r=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),projectId:project.id,modelHash:project.model.hash,label:spec?`${spec.asset} · ${spec.kind} ${spec.percent}%`:label.trim()||'Baseline',experiment:spec?{baselineId,spec}:undefined})});const d=await r.json() as {run:RunRecord;runs:RunRecord[];events:{event:string;created_at:string}[];error:string};if(!r.ok)throw new Error(d.error);if(mounted.current){setRuns(rs=>[d.run,...rs]);setSelected(d.run.id);if(d.run.error)setError(d.run.error)}}catch(e){setError((e as Error).message)}finally{if(mounted.current)setSubmitting(false)}
 }
 async function cancel(id:string){try{const r=await fetch('/api/runs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'cancelled'})});const d=await r.json() as {run:RunRecord;runs:RunRecord[];events:{event:string;created_at:string}[];error:string};if(!r.ok)throw new Error(d.error);await load()}catch(e){setError((e as Error).message)}}
 function exportRun(){const url=URL.createObjectURL(new Blob([JSON.stringify({project:{id:project.id,name:project.name},run:selectedRun,reviewStatus:'Engineering review required'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`run-${selectedRun!.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const analysisView=['Hotspot autopsy','Interventions','Stress test','Comparison','Reports'].includes(view);
 return <div className="live-analysis">
 {error&&<p role="alert" className="error-message">{error}</p>}
 {['Overview','Simulations'].includes(view)&&<>
 <section className="panel simulation-setup"><div><span className="badge blue"><Activity size={13}/>TRUSTED SWMM EXECUTION</span><h2>Run your drainage model</h2><p>The server runs SWMM 5.2.2 using your model's units, event and routing method. Inputs and reports receive immutable fingerprints.</p><div className="solver-limits">500 nodes · 2,000 conduits · 7 days · embedded inputs · 120 seconds per simulation</div></div><div className="simulation-controls"><label htmlFor="run-label">Run label</label><input id="run-label" value={label} maxLength={100} onChange={ev=>setLabel(ev.target.value)} disabled={busy}/><button className="btn primary" onClick={()=>void start()} disabled={busy||!project.model}>{busy?<LoaderCircle className="spin" size={16}/>:<Activity size={16}/>}Run SWMM baseline</button><a href="/benchmark-network.inp" download className="text-button"><Download size={14}/>Synthetic stress benchmark</a><a href="/autopsy-demo.inp" download className="text-button"><Download size={14}/>Autopsy demonstration model</a></div></section>
 {runs.filter(active).map(r=><section className="panel run-progress" key={r.id} aria-live="polite"><div><LoaderCircle className="spin" size={20}/><strong>{r.label} · {r.status}</strong><button className="btn" onClick={()=>void cancel(r.id)}>Cancel run</button></div><p>The server continues running when you leave this page.</p></section>)}
 {result&&<HydraulicMetrics result={result}/>}
 <section className="panel"><div className="panel-header"><div><h2>Simulation history</h2><p>Earlier browser runs are retained with their original verification status.</p></div><button className="text-button" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={14}/>Refresh</button></div>{runs.length?<Table><TableHeader><TableRow>{['RUN / DATE','MODEL','STATUS','TRUST','EVIDENCE'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{runs.map(r=><TableRow key={r.id}><TableCell><strong>{r.label}</strong><small className="block subtle">{new Date(r.createdAt).toLocaleString()}</small></TableCell><TableCell><code>{r.modelHash.slice(0,12)}</code></TableCell><TableCell><span className={`badge ${r.status==='completed'?'green':r.status==='failed'?'red':'amber'}`}>{r.status}</span>{r.error&&<small className="block">{r.error}</small>}</TableCell><TableCell>{r.verification}</TableCell><TableCell><button className="text-button" onClick={()=>{setSelected(r.id);onView('Reports')}}>Inspect</button>{r.reportHash&&<a className="text-button ml-3" href={`/api/runs?id=${r.id}`}>RPT</a>}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><h3>No saved simulations</h3><p>Import an INP model and run its baseline.</p></div>}</section>
 </>}
 {project.model&&['Network model','Hydrology inspector'].includes(view)&&<HydrologyInspector key={project.model.hash} projectId={project.id}/>}
 {project.model&&<AnalysisWorkbench project={project} runs={runs} visible={analysisView}/>}
 {view==='Interventions'&&project.model&&<details className="panel manual-experiments"><summary>Manual controlled experiments</summary><ExperimentStudio projectId={project.id} modelHash={project.model.hash} runs={runs} busy={busy} onRun={(spec,id)=>void start(spec,id)} onInspect={id=>{setSelected(id);onView('Reports')}}/></details>}
 {view==='Reports'&&selectedRun&&<section className="panel inspector-panel"><div className="panel-header"><div><span className={`badge ${selectedRun.verification==='SERVER VERIFIED'?'green':'amber'}`}>{selectedRun.verification}</span><h2>Saved simulation · {selectedRun.label}</h2></div><button className="btn" onClick={exportRun}><Download size={15}/>Export run JSON</button></div>{result?<><HydraulicMetrics result={result}/><p>EPA SWMM {result.engineVersion} · {result.routing} · {result.flowUnits}. Numerical screening: {numericalQuality(result)?'PASS':'FAIL'}; non-convergence {result.nonConvergingPercent??'not reported'}%.</p><HydraulicTable result={result}/>{selectedRun.warnings?<ReviewWarnings warnings={selectedRun.warnings}/>:result.warnings.map(w=><p key={w}>{w}</p>)}</>:<p>{selectedRun.error??'Result unavailable for the current model version.'}</p>}<dl className="hash-list">{[['Source input SHA-256',selectedRun.modelHash],['Experiment input SHA-256',selectedRun.experiment?.inputHash],['Report SHA-256',selectedRun.reportHash],['Engine SHA-256',selectedRun.engineHash]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd><code>{v}</code></dd></div>)}</dl><div className="title-actions"><a className="btn" href={`/api/runs?id=${selectedRun.id}&input=1`}>Original run INP</a>{selectedRun.reportHash&&<a className="btn" href={`/api/runs?id=${selectedRun.id}`}>SWMM report</a>}{selectedRun.outputHash&&<a className="btn" href={`/api/runs?id=${selectedRun.id}&output=1`}>Binary output</a>}</div>{selectedRun.comparison&&<p>Flood-volume reduction: {selectedRun.comparison.volumeReduction?.toFixed(1)??'Unavailable'}%; worsened nodes: {selectedRun.comparison.worsenedNodes.join(', ')||'none above tolerance'}. {selectedRun.comparison.eligible?'Eligible for review':'Review required'}.</p>}</section>}
 {view==='Activity log'&&<section className="panel inspector-panel"><h2>Project audit trail</h2>{activity.length?activity.map((a,i)=><div key={i}><h3>{a.event}</h3><p>{new Date(a.created_at).toLocaleString()}</p></div>):<p>No recorded activity.</p>}</section>}
 {['Overview','Simulations','Network model','Hydrology inspector','Hotspot autopsy','Interventions','Stress test','Comparison','Reports'].includes(view)&&<ReviewNotice/>}
 </div>;
}
