'use client';
import {useState,useEffect,useRef} from 'react';
import {Activity,CheckCircle2,Clock3,Download,FileText,FlaskConical,LoaderCircle,RefreshCw,ShieldCheck,TriangleAlert,Waves,X} from 'lucide-react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {toast} from 'sonner';
import type {Project} from '@/lib/drainage';
import {parseReport,validateRunnableModel,type RunRecord,type SolverResult} from '@/lib/swmm-results';
type Completion={id:string;status:'completed'|'failed'|'cancelled';elapsedMs:number;report?:string;error?:string};
function saveText(name:string,value:string){const url=URL.createObjectURL(new Blob([value],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function LiveAnalysis({project,view,runRequest=0,onView}:{project:Project;view:string;runRequest?:number;onView:(v:string)=>void}){
 const [runs,setRuns]=useState<RunRecord[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[stage,setStage]=useState(''),[error,setError]=useState(''),[unsaved,setUnsaved]=useState<Completion|null>(null),[rawReport,setRawReport]=useState(''),[threshold,setThreshold]=useState(['CFS','GPM','MGD'].includes(project.model?.units??'')?.5:.15),[activity,setActivity]=useState<{event:string;created_at:string}[]>([]),[label,setLabel]=useState('Baseline · embedded model inputs');
 const worker=useRef<Worker|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),active=useRef<RunRecord|null>(null),alive=useRef(true),running=useRef(false),trigger=useRef(runRequest),generation=useRef(0);
 async function load(){const response=await fetch(`/api/runs?projectId=${project.id}`);const data=await response.json() as {runs:RunRecord[];error?:string};if(!response.ok)throw new Error(data.error);if(alive.current){setRuns(data.runs);setSelected(s=>s||data.runs.find(r=>r.modelHash===project.model?.hash&&r.status==='completed')?.id||'')}}
 useEffect(()=>{alive.current=true;load().catch(e=>setError(e.message));return()=>{alive.current=false;generation.current++;worker.current?.terminate();if(timer.current)clearTimeout(timer.current);if(active.current&&running.current){void fetch('/api/runs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:active.current.id,status:'cancelled',elapsedMs:Math.min(600000,Date.now()-Date.parse(active.current.createdAt)),error:'Run cancelled because the project view was closed.'}),keepalive:true})}}},[project.id,project.model?.hash]);
 useEffect(()=>{if(view==='Activity log')fetch(`/api/activity?projectId=${project.id}`).then(async r=>{const d=await r.json() as {events:{event:string;created_at:string}[];error?:string};if(!r.ok)throw new Error(d.error);setActivity(d.events)}).catch(e=>setError(e.message))},[view,project.id]);
 useEffect(()=>{if(runRequest!==trigger.current){trigger.current=runRequest;void start()}},[runRequest]);
 const selectedRun=runs.find(r=>r.id===selected);const current=selectedRun?.modelHash===project.model?.hash;const result=current?selectedRun?.result:undefined;
 function replaceRun(run:RunRecord){setRuns(rs=>[run,...rs.filter(r=>r.id!==run.id)]);setSelected(run.id)}
 function stopWorker(){worker.current?.terminate();worker.current=null;if(timer.current)clearTimeout(timer.current);timer.current=null;running.current=false;setBusy(false)}
 async function persist(body:Completion){try{const response=await fetch('/api/runs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {run:RunRecord;error?:string};if(!response.ok)throw new Error(data.error);if(alive.current){replaceRun(data.run);setUnsaved(null);setStage(body.status==='completed'?'Run complete · results saved':'Run ended');if(body.status==='completed')toast.success('SWMM results saved with model provenance.')}}catch(e){if(alive.current){setError((e as Error).message);setUnsaved(body)}}}
 async function finish(body:Completion){stopWorker();if(body.report)setRawReport(body.report);if(body.status==='completed'&&active.current){try{replaceRun({...active.current,status:'completed',elapsedMs:body.elapsedMs,result:parseReport(body.report!)});}catch(e){body={...body,status:'failed',error:(e as Error).message}}}if(body.error)setError(body.error);await persist(body);}
 async function start(){if(running.current||unsaved)return;if(!project.model){setError('Import a SWMM model first.');return}const token=++generation.current;active.current=null;setError('');setRawReport('');setBusy(true);running.current=true;setStage('Checking model and preparing saved run…');let run:RunRecord|undefined;try{
  const response=await fetch(`/api/models?projectId=${project.id}`);if(!response.ok)throw new Error('The source model could not be loaded.');const bytes=await response.arrayBuffer();if(token!==generation.current||!alive.current)return;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==project.model.hash)throw new Error('The uploaded model changed. Reload the project.');validateRunnableModel(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(token!==generation.current||!alive.current)return;
  const res=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),projectId:project.id,modelHash:hash,label:label.trim()||'Baseline'})});const data=await res.json() as {run:RunRecord;error?:string};if(!res.ok)throw new Error(data.error);run=data.run;if(token!==generation.current||!alive.current){await persist({id:run.id,status:"cancelled",elapsedMs:0,error:"Cancelled before solver start."});return}active.current=run;replaceRun(run);
  const instance=new Worker('/swmm-worker.js');worker.current=instance;instance.onmessage=(event)=>{if(!alive.current||!running.current)return;const m=event.data;if(m.type==='progress'){setStage(m.stage);return}if(m.type==='error'){void finish({id:run!.id,status:'failed',elapsedMs:m.elapsedMs??0,error:m.error});return}if(m.type==='result'){void finish({id:run!.id,status:m.code===0?'completed':'failed',elapsedMs:m.elapsedMs,report:m.report,error:m.code===0?undefined:`SWMM error ${m.code}. ${m.report.match(/.*ERROR\s+\d+[^\n]*/)?.[0]?.trim()??'Download the solver report for details.'}`})}};
  instance.onerror=()=>{if(running.current)void finish({id:run!.id,status:'failed',elapsedMs:Date.now()-Date.parse(run!.createdAt),error:'Solver worker stopped unexpectedly. Download your input and review model size or browser memory.'})};
  timer.current=setTimeout(()=>{void finish({id:run!.id,status:'failed',elapsedMs:120000,error:'Run stopped at the 120-second browser limit. Use a smaller model or longer routing timestep.'})},120000);
  instance.postMessage({bytes},[bytes]);
 }catch(e){stopWorker();setError((e as Error).message);if(run)await persist({id:run.id,status:'failed',elapsedMs:0,error:(e as Error).message})}}
 function cancel(){generation.current++;if(!active.current){stopWorker();setStage("Cancelled before solver start.");return}if(running.current)void finish({id:active.current.id,status:'cancelled',elapsedMs:Math.min(600000,Date.now()-Date.parse(active.current.createdAt)),error:'Cancelled by the engineer.'})}
 const visible=['Overview','Simulations','Hotspot autopsy','Reports','Activity log','Comparison','Interventions'].includes(view);
 if(!visible)return null;
 return <div className="live-analysis">{error&&<div role="alert" className="error-message live-error"><TriangleAlert size={18}/><span>{error}</span><button aria-label="Dismiss run message" onClick={()=>setError('')}><X size={16}/></button></div>}{busy&&<section className="panel run-progress"><div><LoaderCircle className="spin" size={21}/><strong>{stage}</strong><button className="btn" onClick={cancel}>Cancel run</button></div><Progress value={undefined}/><p>SWMM 5.2.2 · isolated browser worker · keep this tab open · 120-second limit</p></section>}{unsaved&&<div className="section-notice"><TriangleAlert size={20}/><span>Result is not saved. Keep this page open or download the report.</span><button className="btn" onClick={()=>void persist(unsaved)}>Retry saving</button>{rawReport&&<button className="btn" onClick={()=>saveText('unsaved-swmm-report.rpt',rawReport)}>Download report</button>}</div>}
 {(view==='Overview'||view==='Simulations')&&<><section className="panel simulation-setup"><div><span className="badge green"><Activity size={13}/>SWMM 5.2.2 · ready</span><h2>Run your drainage model</h2><p>The solver uses the rainfall, inflows, routing method, and time window already in your INP file. No input parameters or units are changed.</p><div className="solver-limits">Up to 500 nodes · 2,000 conduits · 7 days · self-contained inputs</div></div><div className="simulation-controls"><label htmlFor="run-label">Run label</label><input id="run-label" value={label} maxLength={100} onChange={e=>setLabel(e.target.value)} disabled={busy}/><button className="btn primary" onClick={()=>void start()} disabled={busy||!!unsaved||!project.model}>{busy?<LoaderCircle size={16} className="spin"/>:<Activity size={16}/>}Run SWMM baseline</button><a href="/benchmark-network.inp" download className="text-button"><Download size={14}/>Download a runnable sample model</a></div></section>{result&&<RealMetrics result={result}/>}<section className="panel"><div className="panel-header"><div><h2>Simulation history</h2><p>Each result is pinned to its original model SHA-256.</p></div><button className="text-button" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={14}/>Refresh</button></div>{runs.length?<Table><TableHeader><TableRow>{['RUN / DATE','MODEL VERSION','STATUS','DURATION','EVIDENCE'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{runs.map(r=><TableRow key={r.id}><TableCell><strong>{r.label}</strong><small className="block subtle">{new Date(r.createdAt).toLocaleString()}</small></TableCell><TableCell><code>{r.modelHash.slice(0,12)}</code><small className="block subtle">{r.modelHash===project.model?.hash?'Current model':'Earlier model'}</small></TableCell><TableCell><span className={`badge ${r.status==='completed'?'green':r.status==='running'?'blue':'amber'}`}>{r.status}</span></TableCell><TableCell>{(r.elapsedMs/1000).toFixed(2)} s</TableCell><TableCell><button className="text-button" onClick={()=>{setSelected(r.id);onView('Hotspot autopsy')}}>View result</button>{r.reportHash&&<a className="text-button ml-3" href={`/api/runs?id=${r.id}`}>RPT<Download size={13}/></a>}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><Activity/><h3>No simulations yet</h3><p>Import a model, then run a deterministic baseline.</p></div>}</section></>}
 {view==='Hotspot autopsy'&&<>{selectedRun&&!current?<div className="section-notice"><TriangleAlert size={20}/><span>This run belongs to an earlier model version. Download its original report from the run history; it will not be mixed with the current network.</span></div>:result?<><RealMetrics result={result}/><section className="panel"><div className="panel-header"><div><h2>Hydraulic evidence · {selectedRun?.label}</h2><p>Actual SWMM output · no causal diagnosis is inferred from a baseline alone.</p></div><a className="btn" href={`/api/runs?id=${selectedRun!.id}`}><Download size={15}/>Original report</a></div><div className="threshold-control"><label htmlFor="depth-threshold">Ponded-depth screening threshold ({result.depthUnit})</label><input id="depth-threshold" type="number" min="0" step="0.01" value={threshold} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0)setThreshold(n)}}/><span>All flooded nodes remain visible regardless of threshold.</span></div><Tabs defaultValue="hotspots"><TabsList className="mx-5 mb-3"><TabsTrigger value="hotspots">Flooding nodes</TabsTrigger><TabsTrigger value="nodes">All nodes</TabsTrigger><TabsTrigger value="links">Conduits</TabsTrigger></TabsList><TabsContent value="hotspots"><NodeTable result={result} threshold={threshold} floodedOnly/></TabsContent><TabsContent value="nodes"><NodeTable result={result} threshold={threshold}/></TabsContent><TabsContent value="links"><Table><TableHeader><TableRow>{['CONDUIT',`MAX FLOW (${result.flowUnits})`,`VELOCITY (${result.depthUnit}/s)`,'MAX / FULL FLOW','MAX / FULL DEPTH'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{result.links.map(l=><TableRow key={l.id}><TableCell>{l.id}</TableCell><TableCell>{l.maxFlow}</TableCell><TableCell>{l.maxVelocity}</TableCell><TableCell>{l.fullFlowRatio}</TableCell><TableCell>{l.fullDepthRatio}</TableCell></TableRow>)}</TableBody></Table></TabsContent></Tabs></section><Warnings result={result}/><section className="panel provenance"><ShieldCheck size={20}/><div><h3>Reproducible input, transparent execution</h3><p>Engine: EPA SWMM {result.engineVersion} · {result.routing} · {selectedRun!.enginePackage}</p><p>Model SHA-256: <code>{selectedRun!.modelHash}</code></p><p>Report SHA-256: <code>{selectedRun!.reportHash??'Not saved yet'}</code></p><p>Executed in your browser. The server parses and stores the report; it does not independently rerun or certify the result.</p></div></section></>:<section className="panel empty-state tall"><FlaskConical size={32}/><h2>{selectedRun?.status==='failed'?'Simulation failed':'Select a completed baseline'}</h2><p>{selectedRun?.error??'Run your model to inspect actual flooding, node depths, and conduit utilization.'}</p><button className="btn primary" onClick={()=>onView('Simulations')}>Open simulations</button></section>}</>}
 {view==='Reports'&&<section className="panel live-report"><span className="badge amber">ENGINEER REVIEW REQUIRED</span><h2>Simulation evidence package</h2><p>{result?'Download the exact solver report and a summary tied to this model version.':'Complete a baseline before exporting hydraulic evidence.'}</p>{result&&<><Warnings result={result}/><dl><div><dt>Run</dt><dd>{selectedRun!.label}</dd></div><div><dt>Solver</dt><dd>EPA SWMM {result.engineVersion}</dd></div><div><dt>Flow units</dt><dd>{result.flowUnits}</dd></div><div><dt>Routing continuity error</dt><dd>{result.continuityError??'Unavailable'}%</dd></div><div><dt>Source model</dt><dd><code>{selectedRun!.modelHash.slice(0,20)}…</code></dd></div></dl><div className="title-actions"><a className="btn primary" href={`/api/runs?id=${selectedRun!.id}`}><Download size={15}/>Download solver report</a><button className="btn" onClick={()=>saveText(`evidence-${selectedRun!.id}.json`,JSON.stringify({project:{id:project.id,name:project.name,location:project.location},run:selectedRun,reviewStatus:'Not approved',threshold:{pondedDepth:threshold,unit:result.depthUnit},limitations:['Browser-executed result, not independently verified on server.','Baseline results do not establish causality or regulatory compliance.',...result.warnings]},null,2))}><FileText size={15}/>Export evidence JSON</button></div></>}</section>}
 {view==='Activity log'&&<section className="panel"><div className="panel-header"><h2>Recorded project activity</h2><span className="badge neutral">Server audit trail</span></div><div className="timeline">{activity.length?activity.map((a,i)=><div key={i}><Clock3 size={18}/><h3>{a.event}</h3><p>{new Date(a.created_at).toLocaleString()}</p></div>):<p>No recorded activity.</p>}</div></section>}
 {(view==='Interventions'||view==='Comparison')&&<section className="panel empty-state tall"><FlaskConical size={34}/><h2>Baseline evidence comes first</h2><p>{result?'Your baseline is ready. Automated counterfactual modifications and repair ranking for uploaded models are the next integration stage. No example repair is applied to this model.':'Complete a baseline to establish a traceable reference before testing repairs.'}</p><button className="btn primary" onClick={()=>onView(result?'Hotspot autopsy':'Simulations')}>{result?'Review real baseline evidence':'Open simulations'}</button></section>}
 </div>
}
function RealMetrics({result:r}:{result:SolverResult}){return <div className="metrics-grid real-metrics">{[['Flooding nodes',String(r.floodedNodes),'of '+r.nodes.length+' modeled nodes'],['Max reported ponded depth',r.peakPondedDepth===null?'Not reported':r.peakPondedDepth.toFixed(3),r.depthUnit],['Summed node flood volume',r.totalFloodVolume.toFixed(3),r.volumeUnit],['Routing mass-balance error',r.continuityError===null?'Unavailable':String(r.continuityError)+'%','Screening limit ±1%']].map(([title,value,unit])=><div className="metric" key={title}><div className="metric-label">{title}</div><div className="metric-value">{value}</div><div className="metric-note">{unit}</div></div>)}</div>}
function NodeTable({result:r,threshold,floodedOnly=false}:{result:SolverResult;threshold:number;floodedOnly?:boolean}){const nodes=r.nodes.filter(n=>!floodedOnly||n.floodHours>0).sort((a,b)=>b.floodVolume-a.floodVolume);if(!nodes.length)return <div className="empty-state"><CheckCircle2/><h3>No node flooding reported</h3><p>This applies to the modeled event only. Check mass balance and other performance criteria before approving.</p></div>;return <Table><TableHeader><TableRow>{['NODE',`MAX DEPTH (${r.depthUnit})`,`PONDED DEPTH (${r.depthUnit})`,`FLOOD VOL. (${r.volumeUnit})`,'DURATION (h)','SCREENING'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{nodes.map(n=><TableRow key={n.id}><TableCell><strong>{n.id}</strong><small className="block subtle">{n.type}</small></TableCell><TableCell>{n.maxDepth.toFixed(3)}</TableCell><TableCell>{n.pondedDepth===null?'Not reported':n.pondedDepth.toFixed(3)}</TableCell><TableCell>{n.floodVolume.toFixed(3)}</TableCell><TableCell>{n.floodHours.toFixed(2)}</TableCell><TableCell><span className={`badge ${n.pondedDepth!==null&&n.pondedDepth>threshold?'red':n.floodHours>0?'amber':'green'}`}>{n.pondedDepth!==null&&n.pondedDepth>threshold?'Depth exceeds threshold':n.floodHours>0?'Flooding reported':'No flooding reported'}</span></TableCell></TableRow>)}</TableBody></Table>}
function Warnings({result}:{result:SolverResult}){return <section className="panel solver-warnings"><h3><TriangleAlert size={18}/>Solver warnings & interpretation</h3>{result.warnings.map(w=><p key={w}>{w}</p>)}</section>}
