'use client';
import type {UnifiedAnalysisEvidence} from '@/lib/evidence-view';
import {familyNames} from '@/lib/experiments';
import {sameId} from '@/lib/inp';
export function SensitivityVisuals({e}:{e:UnifiedAnalysisEvidence}){
 const ranking=e.diagnosis.ranking,curves=e.diagnosis.curves,selected=e.repairSearch.selected?.firstAdmissible;
 const max=Math.max(1,...ranking.map(r=>Math.abs(r.localElasticity??0)));
 const before=e.baseline.result.nodes.find(n=>sameId(n.id,e.config.targetNode)),after=selected?.run?.result.nodes.find(n=>sameId(n.id,e.config.targetNode));
 return <>
 {ranking.length>0&&<section className="v3-visual-grid">
  <article className="visual-card"><div className="visual-title"><strong>{e.legacy?'Recorded historical sensitivity':'Normalized modeled sensitivity'}</strong><span>Median elasticity · E</span></div>
   {ranking.map((r,i)=><div className="ranking-row" key={r.family+':'+r.asset}><span>{i+1}</span><span className="ranking-label">{familyNames[r.family]} · {r.asset}<small>{r.reliability??'Historical metric'} · {r.monotonicity}</small></span><span className="ranking-track"><i style={{width:`${Math.abs(r.localElasticity??0)/max*100}%`}}/></span><b>E = {r.localElasticity?.toFixed(2)??'—'}</b></div>)}
   <p className="form-hint">Numerical quality → network safety → response reliability → elasticity. Reliability is a response screen, not probability.</p>
  </article>
  <article className="visual-card"><div className="visual-title"><strong>Absolute flood reduction</strong><span>At 20% perturbation</span></div>
   {ranking.map(r=>{const p=curves.find(c=>c.family===r.family&&c.asset===r.asset)?.points.find(p=>p.percent===20);return <p key={r.family+r.asset}>{familyNames[r.family]} · {r.asset}: <strong>{p?.volumeReduction?.toFixed(1)??'Unavailable'}{p?.volumeReduction!=null?'%':''}</strong></p>})}
   <p className="form-hint">Absolute response is shown separately from normalized elasticity.</p>
  </article>
 </section>}
 {curves.length>0&&<section className="visual-card"><h3>Response curves</h3><p>Horizontal axis: parameter change (%). Vertical axis: hotspot flood-volume reduction (%), including negative response.</p>
 {curves.map(c=>{const points=c.points.filter(p=>p.volumeReduction!==null),lo=Math.min(0,...points.map(p=>p.volumeReduction!)),hi=Math.max(1,...points.map(p=>p.volumeReduction!));const y=(v:number)=>65-(v-lo)/(hi-lo)*50;return <details className="response-detail" key={c.family+c.asset}><summary>{familyNames[c.family]} · {c.asset} · {c.monotonicity} · {c.reliability??'Historical'}</summary><svg viewBox="0 0 320 100" role="img" aria-label={`${c.asset} response curve: parameter change versus flood reduction`}><line x1="40" x2="300" y1={y(0)} y2={y(0)} stroke="#9bb1bb"/><text x="0" y="14" fontSize="9">{hi.toFixed(1)}%</text><text x="0" y="68" fontSize="9">{lo.toFixed(1)}%</text><polyline fill="none" stroke="#087b96" strokeWidth="2" points={points.map(p=>`${40+p.percent/20*240},${y(p.volumeReduction!)}`).join(' ')}/>{points.map(p=><g key={p.percent}><circle cx={40+p.percent/20*240} cy={y(p.volumeReduction!)} r="3" fill="#087b96"/><text x={40+p.percent/20*240} y="88" textAnchor="middle" fontSize="10">{p.percent}%</text></g>)}</svg><ul>{c.points.map(p=><li key={p.percent}>{p.percent}% change → {p.volumeReduction?.toFixed(2)??'Unavailable'}% reduction · E {p.elasticity?.toFixed(2)??'Unavailable'} · {p.status}{p.error&&' · '+p.error}</li>)}</ul></details>})}</section>}
 {before&&after&&<section className="visual-card"><div className="visual-title"><strong>Before / after · {e.config.targetNode}</strong><span>Exact selected intervention</span></div><div className="evidence-metrics"><p>Flood volume<br/><strong>{before.floodVolume} → {after.floodVolume}</strong><br/>{e.baseline.result.volumeUnit}</p><p>Maximum node depth<br/><strong>{before.maxDepth} → {after.maxDepth}</strong><br/>{e.baseline.result.depthUnit}</p><p>Flooding duration<br/><strong>{before.floodHours} → {after.floodHours}</strong><br/>hours</p><p>Network harm<br/><strong>{selected?.comparison?.worsenedNodes.length??'Unavailable'} worsened nodes</strong><br/>System volume {e.baseline.result.totalFloodVolume} → {selected?.run?.result.totalFloodVolume} {e.baseline.result.volumeUnit}</p></div></section>}
 {!!e.repairSearch.candidates.length&&<section className="visual-card"><h3>Cross-asset repair search</h3><p>Each candidate uses the same ascending grid within its family bounds; the search stops at its first admissible magnitude.</p>{e.repairSearch.candidates.map(c=><div className="candidate-evidence" key={c.family+c.asset}><h3>{familyNames[c.family]} · {c.asset}</h3><span className={`badge ${c.admissible?'green':c.searchStatus==='INCOMPLETE'?'amber':'red'}`}>{c.admissible?'ADMISSIBLE':c.searchStatus==='INCOMPLETE'?'INCOMPLETE':'NO ADMISSIBLE MAGNITUDE'}</span> <span className={`badge ${c.robustness==='PASS'?'green':c.robustness==='FAIL'?'red':c.robustness==='UNTESTED'?'neutral':'amber'}`}>Robustness: {c.robustness}</span><p>Grid: {c.grid.join(', ')||'Historical'}% · Tested: {c.attempts.map(a=>a.spec.percent+'%').join(', ')||'None'}</p><p>{c.magnitude===null?'No admissible magnitude':`${c.magnitude}% change · ${c.benefit?.toFixed(1)}% hotspot reduction`} · {c.reason}</p></div>)}</section>}
 </>;
}
