'use client';
import type {AnalysisEvidence,NormalizedDiagnosis,SensitivityCurve,TestedHypothesis} from '@/lib/diagnostics';
import {familyNames} from '@/lib/experiments';

export function SensitivityVisuals({e}:{e:AnalysisEvidence}){
 const ranking=e.autopsy?.ranking??[];const curves=e.autopsy?.families??[];const selected=e.search.selected;
 return <>
  {ranking.length>0&&<section className="v3-visual-grid">
   <article className="visual-card"><div className="visual-title"><strong>Normalized sensitivity ranking</strong><span>Modeled sensitivity</span></div>{ranking.map((r,i)=><RankingBar key={`${r.family}:${r.asset}`} row={r} max={Math.max(1,...ranking.map(x=>x.benefit))} index={i}/>)}</article>
   <article className="visual-card"><div className="visual-title"><strong>Response curves</strong><span>Δ flood volume vs. bounded change</span></div>{curves.slice(0,4).map(c=><Curve key={`${c.family}:${c.asset}`} curve={c}/>)}</article>
  </section>}
  {selected&&<BeforeAfter e={e} selected={selected}/>}<RepairCandidates e={e}/>
 </>;
}
function RankingBar({row,max,index}:{row:NormalizedDiagnosis;max:number;index:number}){const width=Math.max(4,Math.round((row.benefit/max)*100));return <div className="ranking-row"><span className="rank-num">{index+1}</span><span className="ranking-label">{familyNames[row.family]} · {row.asset}<small>{row.localElasticity===null?'elasticity unavailable':`E ${row.localElasticity.toFixed(2)} · ${row.monotonicity.toLowerCase()}`}</small></span><span className="ranking-track"><i style={{width:`${width}%`}}/></span><b>{row.benefit.toFixed(1)}%</b></div>}
function Curve({curve}:{curve:SensitivityCurve}){const points=curve.points.filter(p=>p.volumeReduction!==null);const max=Math.max(1,...points.map(p=>p.volumeReduction??0));return <div className="curve-row"><div><strong>{familyNames[curve.family]}</strong><small>{curve.asset} · {curve.modeledSensitivity} · {curve.monotonicity}</small></div><svg viewBox="0 0 220 42" role="img" aria-label={`${familyNames[curve.family]} response curve`}><polyline fill="none" stroke="currentColor" strokeWidth="2" points={points.map((p,i)=>`${8+(i*204)/Math.max(1,points.length-1)},${36-((p.volumeReduction??0)/max)*30}`).join(' ')}/>{points.map((p,i)=><circle key={i} cx={8+(i*204)/Math.max(1,points.length-1)} cy={36-((p.volumeReduction??0)/max)*30} r="2.5" fill="currentColor"/>)}</svg></div>}
function BeforeAfter({e,selected}:{e:AnalysisEvidence;selected:TestedHypothesis}){const target=e.config.targetNode;const before=e.baseline.result.nodes.find(n=>n.id.toUpperCase()===target.toUpperCase());const after=selected.run?.result.nodes.find(n=>n.id.toUpperCase()===target.toUpperCase());if(!before||!after)return null;const max=Math.max(before.floodVolume,after.floodVolume,0.001);return <section className="visual-card before-after"><div className="visual-title"><strong>Before / after at hotspot {target}</strong><span>Selected admissible intervention</span></div><div className="ba-bars"><div><span>Baseline</span><i style={{height:`${Math.max(8,before.floodVolume/max*120)}px`}}/><b>{before.floodVolume.toFixed(3)}</b></div><div><span>After</span><i style={{height:`${Math.max(8,after.floodVolume/max*120)}px`}}/><b>{after.floodVolume.toFixed(3)}</b></div><p>{e.baseline.result.volumeUnit}</p></div></section>}
function RepairCandidates({e}:{e:AnalysisEvidence}){const cs=e.repairSearch?.candidates??[];if(!cs.length)return null;return <section className="visual-card repair-candidates"><div className="visual-title"><strong>Cross-asset minimal repair candidates</strong><span>Admissibility → robustness → smaller magnitude → benefit</span></div>{cs.map(c=><div className="candidate-row" key={`${c.family}:${c.asset}`}><strong>{familyNames[c.family]} · {c.asset}</strong><span className={`badge ${c.admissible?'green':'amber'}`}>{c.admissible?'ADMISSIBLE':'UNTESTED / REJECTED'}</span><span>{c.magnitude===null?'No accepted magnitude':`${c.magnitude}% · ${c.benefit?.toFixed(1)??'—'}% benefit`}</span></div>)}</section>}
